### ISSUE TITLE
Vertical sequencer patch: double or skipped steps

### ISSUE THREAD

**Issue by norjad** [wir35/marf#25]
Beta 5

The vertical sequencer patch works much much better now! The glitches we heard before (step starts with previous cv and jumps to the new cv) are gone. I tried it with 1/16 note sequences und pushed it up to 300 bpm. No glitches (of that kind).

But another issue occurs occasionally now:
1) Sometimes the next step will be played too early. In this case you hear that the rhythm stumbles.
2) Sometimes a step will not readout/play the new pitch. Instead the same pitch will be played by two consecutive steps. This results in offsetting the entire sequence by one step. Without touching any fader the generated melody will sound completely different afterwards. (Of course this is only audible if not all faders are set to the same EXTERNAL CV).

My impression is that 2) happens more often than 1). It's easier to see/hear what happens if the cv/pulse sequence is slow, something like 20 bpm.

When I feed the same pulse that drives the MARF's START/STOP (NOTE ON Out of the225e) to the sequencer of my 208C, the 208C sequencer does not skip oder double any steps. This means the issue lies in how the MARF advances the steps, not in the pulse itself.

(P. S.: I just noted that, when I drive the MARF's START/STOP with a Clock out of the 225e instead of a NOTE Out, I hear the pitch glitches of Beta 4 again. I have to investigate this further by comparing the waveform of both pulses...)

**Comment by norjad** [comment]
![251e_Yellow_Note_Cyan_Pulse](https://user-images.githubusercontent.com/52635921/179372883-6a859d61-30ec-4bf0-9951-f2ac70dfa442.jpg)

Here you see the two pulses from the 251e:
– Top/Yellow: The stepped pulse from the NOTE ON out.
– Bottom/Cyan: The gate pulse from the Clock out.

This explains why there are still pitch glitches when using the Clock (gate) pulses to trigger MARF's steps: The rising edge of the Clock (gate) pulse is early compared to the rising edge of the NOTE ON (stepped) pulse. So this might be a 252 specific issue.

I still have to check if the rhythmical issues (double or skipped steps) are related to the length of the sustain phase of the stepped pulses. I don't think so because MARF's START/STOP input should only detect the rising edge, but I'll shorten the length of the incoming notes and see if this changes anything.

**Comment by maxl0rd** [comment]
Thanks for digging in to this. Could you document the whole patch where it skips steps. Might you be using both afgs or just one?

**Comment by norjad** [comment]
I'm using just one AFG. I have a 251e on order, but it could take months until it arrives, so if one of you could check this with a 251e? Perhaps the latency needs to be slightly bigger to make it rock solid?

Here's a shaky video (too big to embed it here):
https://drive.google.com/file/d/1S4qzVa263joCwKgu0GZHa0vbHpYMrStZ/view?usp=sharing


P. S.: I'll go on a two week vacation next Tuesday, so I won't be able to try anything whithin the next two or three weeks.

**Comment by DARKSPARKLER** [comment]
I noticed in your video that you have the time range for the stages set to 2-30sec and the time multiplier knobs are turned all the way up to x4. I find that the internal time settings can still affect the timing when clocked externally, and I will periodically get dropped/skipped steps when the MARF's internal time is set to long intervals. It's best to have the internal time settings set to a range that is closer to, or faster than the timing of the external clock source.

**Comment by norjad** [comment]
Thanks, I forgot about that. I'll give it a try when I'm back from my vacation and see if this solves the issue.

**Comment by DARKSPARKLER** [comment]
I finally got this firmware version loaded onto my module and I am finding some internal and external clocking anomalies, so your problems with clocking might not have to do with the internal time settings that I had suggested before.

**Comment by maxl0rd** [comment]
I am back from holiday. Thanks to this report I worked out a logical bug in the new pulse handling logic. I think it will be easy to fix, but might take some time to verify thoroughly.

**Comment by maxl0rd** [comment]
Repro-ed and fixed as of 822467ef

**Comment by norjad** [comment]
Beta 6

The issue is still present in beta 6. I also had a situation where the speed of the sequence went crazy for one or two seconds, almost up to audio rate, and then it went back to normal. This only happened once in about 30 minutes of testing, but the main issue (double or skipped steps) happened quite frequently.

**Comment by maxl0rd** [comment]
Reopening.

**Comment by maxl0rd** [comment]
Could you try clocking from the mod osc on your 259? Just set it to square, low range and patch the cv out to the start and stop on the 248. I’d like to see if you still get that behavior. It’s possibly an artifact of using the 225.

**Comment by norjad** [comment]
That wouldn't produce a pitch cv sequence in sync with pulses, but I just tried it with my 208c: CVs from the 5 step sequencer to MARF's external in A. 208c's sequencer and MARF's START/STOP clocked by the 208c's pulser: same result, so it does not seem to be restricted to the 225e.

As mentioned earlier, it would be great if some of you could give it a try with the 251e. Mine won't arrive before October/November.

**Comment by norjad** [comment]
I just removed the patch chord between MARF's START and STOP and set each step to STOP instead: no more double or skipped steps since ten minutes now! YEAH!

As far as I know both methods should produce the same result, so you might want to look into why patching START/STOP produces artefacts and software STOPs don't – but at least this solves the problem with the vertical sequencer patch.

**Comment by maxl0rd** [comment]
I am traveling again right now, so away from my test system. However, I have a nagging thought.

It's possible that this behavior could be a symptom of an intermittent connection at your stop jack. The previous software might have tolerated it a little bit better, but the new (interrupt-based) software might have made it worse.

If you are also feeling paranoid, I would reflow the wire jumper connecting to the stop jacks. It's possible there is a cold solder joint there. I got one myself after handling the module too much, and I had to touch up a few of the solder joints.

**Comment by norjad** [comment]
Never say never, but I don't think so. I just tried the same patch with AFG 2: exactly the same result. I think it's very unlikely that both STOP jacks have a cold solder joint. My MARF was built by Steffen (SaModular) and I hardly ever used the STOP jack of AFG 2 yet.

Perhaps give it a try with your system once you're back. With my system the difference is very obvious: no artefacts at all whith programmed STOPs – frequent artefacts whith wired START/STOP.

**Comment by DARKSPARKLER** [comment]
Here's a few thoughts on clocking the MARF through the start and stop inputs...

https://www.youtube.com/watch?v=ZB5uES6uXTE

**Comment by norjad** [comment]
Thanks so much for the background and insights, Kyle! I wasn't really aware of the "Soft Sync" mode. I'm just listening to a noise pulse, triggering AFG 2 with one OSC, AFG 1 with another OSC is following in Soft Sync mode, and TIME MULTIPLIER 1 is automated by a random CV: sounds like a Hungarian Jazz band from the future. This is so much fun!

Back to our topic: I tried wired external sync again now. I hear double/skipped steps in Soft and in Hard Sync mode. I'm wondering why you don't. In my experience it helps a lot to set some octave shift, envelope trigger or Slope steps. This way you immediately hear when the pattern shifts/slips. It's also really helpful to try everything with external and with internal pitch sequences. Some artefacts are more obvious with internal, others with external pitch sequences.

On wired Start/Stop vs. programmed Stops: To me it always felt weird to send the same pulse simultaneously to a Start AND a Stop input. This is really counter-intuitive.
Of course the wired Stop is useful in some patches, because it works in real time vs. pre-programmed. But it looks like the best way to go is to use programmed Stops for continuous external clocking and the wired Start/Stop for "more weird" things.
